### ISSUE TITLE
Надо бы проверочку поставить :)

### ISSUE THREAD

**Issue by andkon13** [programmis/socket_chat#1]
public static function prepareToSend($type, $data = [], UserInterface $user = null)
    {
        /** @var User $user */
        $message = [
            'system' => $type,
            'data'   => $data
        ];
        switch ($type) {
            case self::TYPE_USER_INFO:
            case self::TYPE_USER_ABOUT_ME_INFO:
            case self::TYPE_USER_REMOVED:
            case self::TYPE_USER_CONNECTED:
            case self::TYPE_USER_DISCONNECTED:
                $message = array_merge($message, [
                    User::CONTAINER => $user->getInfo() // $user must by **NUUUUUUULL**...

**Comment by programmis** [comment]
Да святится имя твое, о величайший из разработчиков, о Team Leader всех Team Leader'ов.
Да будет твой дом всегда полон зерна.
Да сопутствует тебе повсюду удача.
